### ISSUE TITLE
Can u show me how u implemented your firestore? 

### ISSUE THREAD

**Issue by uzairpawaskar** [yashpaneliya/PDF-Viewer-Flutter#1]
i just want to know how u implemented your firestore because i uploaded pdf in in firebase storage and it didn't show anything.. did u entered link in the firestore and that link is getting open or u uploaded the pdfs? where?

**Comment by yashpaneliya** [comment]
First I uploaded pdf files in firebase storage and then added the link of firebase storage in firestore and opened the files through links.

Firebase storage:
![image](https://user-images.githubusercontent.com/58077762/79855016-fdfb2480-83e7-11ea-904a-3fe886640608.png)

Firestore:
![image](https://user-images.githubusercontent.com/58077762/79854939-e1f78300-83e7-11ea-8ff0-0ae86eed3411.png)

**Comment by yashpaneliya** [comment]
Hope this will help you!!!!

**Comment by uzairpawaskar** [comment]
thanks a lot this solved my issue..
